[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerContext = "."

[deploy]
# Procfile will handle the start command
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100
